version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./BE
    container_name: node-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - PORT=3000

  frontend:
    build: ./FE
    container_name: react-frontend
    ports:
      - "4173:80"
    depends_on:
      - backend

volumes:
  mongo-data:
