services:
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ahha90tU
      MONGO_INITDB_ROOT_PASSWORD: janlkjf8e3-04ualkdsfj
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./BE
    container_name: node-backend
    expose:
      - "3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://ahha90tU:janlkjf8e3-04ualkdsfj@mongodb:27017
      - PORT=3000

  frontend:
    build: 
      context: ./FE
      args:
        VITE_API_BASE_URL: /api
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
